import type { Product } from "./data";

// [slug, name, category, price (NGN), unit, emoji, rating, reviews, compare-at price (0 = none), badge, description]
type Row = [string, string, string, number, string, string, number, number, number, string, string];

const rows: Row[] = [
  // Women
  ["floral-wrap-dress", "Floral wrap midi dress", "Women", 34500, "Sizes XS–XL", "👗", 4.8, 187, 41000, "New", "A flowing wrap dress in a soft botanical print with flutter sleeves and a flattering tie waist."],
  ["oatmeal-knit-cardigan", "Oatmeal knit cardigan", "Women", 28500, "Sizes XS–XL", "🧶", 4.7, 142, 0, "", "A cosy, textured cardigan in a warm oat shade that layers over everything."],
  ["denim-jacket-women", "Light-wash denim jacket", "Women", 31000, "Sizes XS–XL", "🧥", 4.6, 98, 0, "", "A classic cropped denim jacket with a worn-in wash and a relaxed fit."],
  ["camel-pleated-skirt", "Camel pleated midi skirt", "Women", 22500, "Sizes XS–XL", "👗", 4.8, 121, 26000, "", "Fine knife pleats that move beautifully, finished with an elastic waist for easy wear."],
  ["ivory-blazer", "Tailored ivory blazer", "Women", 46000, "Sizes XS–XL", "🥼", 4.9, 76, 0, "Best seller", "A sharply tailored single-breasted blazer that takes work wear from desk to dinner."],
  ["black-wide-trousers", "Wide-leg tailored trousers", "Women", 26500, "Sizes XS–XL", "👖", 4.7, 204, 0, "", "High-rise trousers with a fluid wide leg and a clean, pressed front crease."],
  ["white-poplin-blouse", "White poplin blouse", "Women", 19500, "Sizes XS–XL", "👚", 4.8, 233, 0, "", "A crisp cotton poplin blouse that is endlessly easy to style."],
  // Men
  ["oxford-shirt", "Oxford button-down shirt", "Men", 18500, "Sizes S–XXL", "👔", 4.7, 256, 0, "", "A softly brushed Oxford shirt in sky blue with a classic button-down collar."],
  ["khaki-chinos", "Slim khaki chinos", "Men", 21500, "Sizes 28–40", "👖", 4.6, 318, 25000, "", "Stretch cotton chinos with a tapered leg that look sharp and feel easy all day."],
  ["navy-knit-polo", "Navy knit polo", "Men", 16500, "Sizes S–XXL", "👕", 4.7, 174, 0, "New", "A fine-knit polo in deep navy with a soft collar and a smart, relaxed drape."],
  ["indigo-denim-jacket", "Indigo denim jacket", "Men", 38500, "Sizes S–XXL", "🧥", 4.8, 109, 0, "", "A rugged trucker jacket in dark indigo selvedge-style denim that ages beautifully."],
  ["leather-belt", "Brown leather belt", "Men", 11500, "Sizes 30–42", "🪢", 4.6, 142, 0, "", "A full-grain leather belt with a brushed steel buckle, built to last."],
  ["olive-cap", "Olive baseball cap", "Men", 6500, "One size", "🧢", 4.5, 211, 0, "", "A soft, unstructured cotton cap with an adjustable strap in a versatile olive."],
  ["grey-wool-sweater", "Grey wool crewneck sweater", "Men", 27500, "Sizes S–XXL", "🧶", 4.8, 87, 32000, "", "A warm, marled wool-blend crewneck with a ribbed trim and a classic fit."],
  ["beige-shorts", "Tailored beige shorts", "Men", 14500, "Sizes 28–40", "🩳", 4.5, 132, 0, "", "Lightweight cotton shorts with a clean tailored cut for warm weekends."],
  ["charcoal-overcoat", "Charcoal wool overcoat", "Men", 89000, "Sizes S–XXL", "🧥", 4.9, 54, 105000, "Sale", "A double-breasted overcoat in a soft wool blend, cut for a polished silhouette."],
  // Shoes
  ["white-leather-sneakers", "White leather sneakers", "Shoes", 32500, "Sizes 36–46", "👟", 4.8, 412, 0, "Best seller", "Minimal low-top sneakers in smooth leather with a cushioned insole."],
  ["grey-chunky-runners", "Grey chunky runners", "Shoes", 36000, "Sizes 36–46", "👟", 4.6, 238, 42000, "", "Retro-inspired runners with a breathable mesh upper and a bouncy chunky sole."],
  ["black-chelsea-boots", "Black Chelsea boots", "Shoes", 52000, "Sizes 38–46", "🥾", 4.9, 167, 0, "", "Sleek leather Chelsea boots with elastic side panels and a durable rubber sole."],
  ["tan-leather-loafers", "Tan leather loafers", "Shoes", 38500, "Sizes 38–46", "👞", 4.7, 144, 0, "", "Hand-finished penny loafers in warm tan leather, smart with or without socks."],
  ["leather-slide-sandals", "Leather slide sandals", "Shoes", 19500, "Sizes 36–46", "🩴", 4.6, 289, 0, "", "Contoured cork footbed sandals with two soft leather straps."],
  ["canvas-high-tops", "Canvas high-top sneakers", "Shoes", 24500, "Sizes 36–46", "👟", 4.7, 355, 0, "", "Everyday canvas high-tops with a vulcanised sole and a timeless silhouette."],
  ["block-heel-pumps", "Nude block-heel pumps", "Shoes", 29500, "Sizes 35–42", "👠", 4.7, 118, 0, "New", "Comfortable block heels in a soft nude leather, made for long days."],
  ["olive-hiking-boots", "Olive hiking boots", "Shoes", 58000, "Sizes 38–46", "🥾", 4.8, 96, 66000, "", "Waterproof, grippy hiking boots with ankle support for trails and rainy days."],
  ["knit-house-slippers", "Knit house slippers", "Shoes", 9500, "Sizes 36–44", "🥿", 4.5, 187, 0, "", "Soft knit slippers with a memory-foam insole and a non-slip sole."],
  // Kids
  ["kids-denim-jacket", "Kids denim jacket", "Kids", 17500, "Ages 2–10", "🧥", 4.7, 84, 0, "", "A tough little denim jacket with soft stretch and room to grow."],
  ["kids-white-sneakers", "Kids white sneakers", "Kids", 14500, "Sizes 24–35", "👟", 4.8, 203, 0, "", "Easy lace-up sneakers with a flexible sole and a wipe-clean finish."],
  ["kids-mustard-backpack", "Kids mustard backpack", "Kids", 12500, "1 backpack", "🎒", 4.7, 128, 0, "New", "A lightweight school backpack with padded straps and a roomy main pocket."],
  ["baby-sage-romper", "Baby sage romper", "Kids", 8900, "Ages 0–24 months", "🍼", 4.9, 242, 0, "Best seller", "A buttery-soft cotton romper with snap fastenings for easy changes."],
  ["kids-grey-hoodie", "Kids grey hoodie", "Kids", 11500, "Ages 2–12", "🧥", 4.7, 156, 13500, "", "A fleece-lined pullover hoodie that stands up to playground adventures."],
  ["kids-yellow-raincoat", "Kids yellow raincoat", "Kids", 15500, "Ages 2–10", "☔", 4.8, 91, 0, "", "A bright waterproof raincoat with a hood and taped seams for puddle days."],
  ["kids-lunch-box", "Insulated kids lunch box", "Kids", 8500, "1 lunch box", "🍱", 4.6, 175, 0, "", "A soft insulated lunch box that keeps meals fresh until lunchtime."],
  ["kids-round-sunglasses", "Kids round sunglasses", "Kids", 5500, "Ages 3–10", "🕶️", 4.5, 102, 0, "", "Flexible, UV-protective round sunglasses made for small faces."],
  ["kids-striped-pyjamas", "Kids striped pyjama set", "Kids", 9800, "Ages 2–12", "🌙", 4.8, 133, 0, "", "A soft two-piece cotton pyjama set in classic breton stripes."],
  // Toys & Games
  ["wooden-building-blocks", "Wooden building blocks", "Toys & Games", 14500, "48 pieces", "🧱", 4.9, 221, 0, "Best seller", "A colourful set of smooth wooden blocks that builds imagination and balance."],
  ["plush-teddy-bear", "Plush teddy bear", "Toys & Games", 11500, "35cm", "🧸", 4.9, 387, 0, "", "An ultra-soft, huggable teddy for bedtime stories and big feelings."],
  ["rc-toy-car", "Remote-control racing car", "Toys & Games", 19500, "1 car + remote", "🏎️", 4.5, 164, 24000, "", "A fast, durable RC car with rechargeable batteries and a responsive controller."],
  ["family-board-game", "Family board game", "Toys & Games", 13500, "2–6 players", "🎲", 4.7, 109, 0, "", "A quick-to-learn strategy game for family nights and friendly rivalry."],
  ["jigsaw-puzzle", "Safari jigsaw puzzle", "Toys & Games", 7500, "100 pieces", "🧩", 4.6, 138, 0, "", "A vibrant illustrated jigsaw with sturdy, easy-to-grip pieces."],
  ["wooden-train-set", "Wooden train set", "Toys & Games", 24500, "32 pieces", "🚂", 4.8, 77, 0, "New", "A charming wooden railway with a locomotive, carriages and curved track."],
  ["kids-art-set", "Kids art set", "Toys & Games", 9500, "42 pieces", "🎨", 4.8, 195, 0, "", "Pencils, watercolours and brushes in a handy tin for little artists."],
  ["toy-robot", "Interactive toy robot", "Toys & Games", 27500, "1 robot", "🤖", 4.5, 86, 32000, "", "A walking, talking robot with lights, music and dance moves."],
  ["stacking-rings", "Rainbow stacking rings", "Toys & Games", 5900, "1 set", "🌈", 4.9, 264, 0, "", "A classic stacking toy that builds hand-eye coordination."],
  // Pets
  ["plush-dog-bed", "Calming plush dog bed", "Pets", 21500, "Medium", "🐶", 4.8, 213, 25000, "", "A deep, donut-shaped bed with a raised rim for cosy, secure naps."],
  ["cat-tree-tower", "Cat tree tower", "Pets", 38500, "1 tower", "🐱", 4.7, 92, 0, "", "A multi-level cat tower with sisal posts, a perch and a hideaway condo."],
  ["leather-dog-leash-set", "Leather collar & leash set", "Pets", 14500, "Medium", "🦮", 4.8, 147, 0, "", "A matching full-grain leather collar and leash that softens with wear."],
  ["ceramic-pet-bowl", "Ceramic pet bowl", "Pets", 5500, "1 bowl", "🥣", 4.7, 118, 0, "", "A heavy, non-slip ceramic bowl that is easy to clean and dishwasher safe."],
  ["cat-toy-mice", "Cat toy mice (set of 5)", "Pets", 3500, "5 toys", "🐭", 4.6, 301, 0, "", "Plush catnip-filled mice that bring out every cat's hunting instincts."],
  ["dog-chew-set", "Natural dog chew set", "Pets", 6500, "3 chews", "🦴", 4.5, 176, 0, "", "Durable rope and bone chews that keep teeth clean and dogs busy."],
  ["soft-pet-carrier", "Soft pet carrier", "Pets", 26500, "Up to 8kg", "🧳", 4.7, 69, 0, "", "An airline-style soft carrier with ventilation panels and a padded base."],
  ["dog-winter-coat", "Dog winter coat", "Pets", 12500, "Sizes S–XL", "🧥", 4.6, 84, 0, "", "A warm, water-resistant coat with a fleece lining and a reflective trim."],
  ["cat-scratch-pad", "Cat scratch pad", "Pets", 4500, "1 pad", "🐾", 4.5, 223, 0, "", "A corrugated scratcher that protects your furniture and keeps claws healthy."],
  // Kitchen & Dining
  ["ceramic-dinnerware-set", "Ceramic dinnerware set", "Kitchen & Dining", 36500, "12 pieces", "🍽️", 4.8, 164, 42000, "Best seller", "Plates and bowls in a soft matte white glaze, oven and microwave safe."],
  ["cast-iron-skillet", "Cast iron skillet", "Kitchen & Dining", 18500, "26cm", "🍳", 4.9, 298, 0, "", "A pre-seasoned skillet that sears beautifully and lasts for generations."],
  ["chef-knife-board", "Chef knife & board set", "Kitchen & Dining", 27500, "2 pieces", "🔪", 4.8, 133, 0, "", "A razor-sharp chef knife paired with an end-grain wooden chopping board."],
  ["glass-carafe-set", "Glass carafe & tumbler set", "Kitchen & Dining", 12500, "3 pieces", "🥛", 4.6, 87, 0, "", "A clear glass carafe with two tumblers, perfect for water at the table."],
  ["steel-cooking-pot", "Stainless steel cooking pot", "Kitchen & Dining", 22500, "5L", "🍲", 4.7, 176, 0, "", "A heavy-bottomed pot with a tight glass lid and even heat distribution."],
  ["french-press", "French press coffee maker", "Kitchen & Dining", 14500, "800ml", "☕", 4.7, 241, 17000, "", "A glass press with a stainless frame for rich, full-bodied coffee."],
  ["copper-pour-over-kettle", "Copper pour-over kettle", "Kitchen & Dining", 31500, "1L", "🫖", 4.8, 72, 0, "New", "A gooseneck kettle with a precise pour for pour-over coffee and tea."],
  ["speckled-mug-set", "Speckled ceramic mug set", "Kitchen & Dining", 13500, "4 mugs", "🍵", 4.9, 305, 0, "", "Four hand-glazed speckled mugs with generous handles."],
  ["wooden-spice-rack", "Wooden spice rack", "Kitchen & Dining", 16500, "8 jars", "🧂", 4.6, 94, 0, "", "A tiered acacia rack with eight corked glass jars and labels."],
  // Electronics
  ["slim-laptop", "Slim 14-inch laptop", "Electronics", 685000, "16GB / 512GB", "💻", 4.8, 64, 749000, "New", "A light aluminium laptop with a crisp display and all-day battery life."],
  ["mechanical-keyboard", "Compact mechanical keyboard", "Electronics", 38500, "75% layout", "⌨️", 4.7, 148, 0, "", "A wireless mechanical keyboard with tactile switches and a satisfying sound."],
  ["ergonomic-mouse", "Ergonomic wireless mouse", "Electronics", 24500, "1 mouse", "🖱️", 4.6, 213, 0, "", "A contoured, quiet-click mouse with multi-device Bluetooth."],
  ["tablet-folio", "10-inch tablet with folio", "Electronics", 235000, "128GB", "📱", 4.6, 91, 265000, "", "A bright, responsive tablet with a protective folio stand for work and play."],
  ["mirrorless-camera", "Mirrorless camera kit", "Electronics", 520000, "24MP + lens", "📷", 4.9, 47, 0, "", "A compact mirrorless camera with a versatile zoom lens for stills and video."],
  ["smart-speaker", "Smart speaker", "Electronics", 29500, "1 speaker", "🔈", 4.5, 187, 34000, "", "A fabric-finish speaker with voice control and room-filling sound."],
  ["game-controller", "Wireless game controller", "Electronics", 32500, "1 controller", "🎮", 4.8, 224, 0, "", "A precise, comfortable controller for PC, console and mobile gaming."],
  ["e-reader", "E-ink e-reader", "Electronics", 98000, "16GB", "📖", 4.8, 108, 0, "", "A glare-free e-reader with a warm backlight and weeks of battery."],
  ["laptop-stand", "Aluminium laptop stand", "Electronics", 13500, "Foldable", "🧰", 4.7, 176, 0, "", "A foldable stand that lifts your screen to eye level and stores flat."],
  // Home & Living
  ["linen-pillow-set", "Linen throw pillows (set of 3)", "Home & Living", 18500, "3 pillows", "🛋️", 4.8, 142, 0, "", "Textured linen cushions in layered neutrals, with removable covers."],
  ["jute-round-rug", "Woven jute round rug", "Home & Living", 28500, "150cm", "🟤", 4.7, 88, 0, "", "A handwoven jute rug that adds warmth and texture to any room."],
  ["ceramic-table-lamp", "Ceramic table lamp", "Home & Living", 24500, "1 lamp", "💡", 4.8, 119, 29000, "", "A softly glazed ceramic base with a linen shade for warm, ambient light."],
  ["gold-round-mirror", "Gold-frame round mirror", "Home & Living", 32500, "70cm", "🪞", 4.7, 73, 0, "", "A slim metal-framed round mirror that brightens entryways and bedrooms."],
  ["earth-vase-set", "Earth-tone vase set", "Home & Living", 17500, "3 vases", "🏺", 4.8, 101, 0, "New", "Three handmade ceramic vases in complementary terracotta, sand and sage."],
  ["oak-bookshelf", "Oak open bookshelf", "Home & Living", 68000, "4 shelves", "📚", 4.6, 58, 0, "", "A clean-lined oak bookshelf with adjustable shelves and sturdy joinery."],
  ["linen-bedding-set", "Washed linen bedding set", "Home & Living", 54000, "Queen", "🛏️", 4.9, 166, 62000, "Best seller", "A breathable washed-linen duvet cover and pillowcases that get softer with every wash."],
  ["abstract-art-print", "Framed abstract art print", "Home & Living", 21500, "40 × 50cm", "🖼️", 4.6, 64, 0, "", "A calm, modern abstract print in a slim black frame, ready to hang."],
  ["rolled-bath-towels", "Cotton bath towels (set of 3)", "Home & Living", 15500, "3 towels", "🛁", 4.8, 207, 0, "", "Plush, absorbent cotton towels in crisp white."],
];

export const extraProducts: Product[] = rows.map(([slug, name, category, price, unit, emoji, rating, reviews, compareAt, badge, description]) => ({
  slug,
  name,
  category,
  price,
  unit,
  emoji,
  image: `/images/g/${slug}.jpg`,
  tone: "cream",
  ...(badge ? { badge } : {}),
  rating,
  reviews,
  ...(compareAt ? { compareAt } : {}),
  description,
  note: "Easy 7-day returns on every order.",
}));
