import { extraProducts } from "./catalogExtra";

export type Product = {
  productId?: string;
  variantId?: string;
  slug: string;
  name: string;
  category: string;
  price: number;
  unit: string;
  emoji: string;
  image: string;
  tone: string;
  badge?: string;
  rating?: number;
  reviews?: number;
  compareAt?: number;
  description: string;
  note: string;
};

export const categories = [
  { name: "Women", slug: "women", emoji: "👗", count: "0", image: "/images/g/floral-wrap-dress.jpg" },
  { name: "Men", slug: "men", emoji: "👕", count: "0", image: "/images/g/oxford-shirt.jpg" },
  { name: "Kids", slug: "kids", emoji: "🧸", count: "0", image: "/images/g/kids-yellow-raincoat.jpg" },
  { name: "Shoes", slug: "shoes", emoji: "👟", count: "0", image: "/images/g/white-leather-sneakers.jpg" },
  { name: "Home & Living", slug: "home-living", emoji: "🛋️", count: "0", image: "/images/g/ceramic-table-lamp.jpg" },
  { name: "Kitchen & Dining", slug: "kitchen-dining", emoji: "🍳", count: "0", image: "/images/g/cast-iron-skillet.jpg" },
  { name: "Beauty", slug: "beauty", emoji: "🧴", count: "0", image: "/images/p/body-lotion.jpg" },
  { name: "Electronics", slug: "electronics", emoji: "🎧", count: "0", image: "/images/p/wireless-headphones.jpg" },
  { name: "Sports", slug: "sports", emoji: "🏋️", count: "0", image: "/images/p/yoga-mat-set.jpg" },
  { name: "Accessories", slug: "accessories", emoji: "👜", count: "0", image: "/images/p/structured-handbag.jpg" },
  { name: "Toys & Games", slug: "toys-games", emoji: "🧩", count: "0", image: "/images/g/wooden-building-blocks.jpg" },
  { name: "Pets", slug: "pets", emoji: "🐾", count: "0", image: "/images/g/plush-dog-bed.jpg" },
  { name: "Gifts", slug: "gifts", emoji: "🎁", count: "0", image: "/images/p/festive-gift-box.jpg" },
  { name: "Groceries", slug: "groceries", emoji: "🧺", count: "0", image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&q=85" },
];

export const products: Product[] = [
  {
    slug: "sunrise-citrus-box",
    name: "Nigerian citrus box",
    category: "Groceries",
    price: 6800,
    unit: "box / 8 pieces",
    emoji: "🍊",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&q=85",
    tone: "orange",
    badge: "Picked today",
    description: "A bright box of Nigerian oranges, tangerines and lemons selected for breakfast, juicing and sharing.",
    note: "Sourced from local growers and delivered at its peak.",
  },
  {
    slug: "garden-crunch-lettuce",
    name: "Ugu leaf bundle",
    category: "Groceries",
    price: 2400,
    unit: "2 fresh bundles",
    emoji: "🥬",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85",
    tone: "green",
    badge: "Just in",
    description: "Fresh, deep-green ugu leaves for soups, smoothies and everyday Nigerian cooking.",
    note: "Harvested locally and packed within 48 hours.",
  },
  {
    slug: "cloud-nine-sourdough",
    name: "Agege bread loaf",
    category: "Groceries",
    price: 4500,
    unit: "650g loaf",
    emoji: "🍞",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85",
    tone: "wheat",
    badge: "Baked this morning",
    description: "Soft, pillowy Agege-style bread with the golden crust made for akara, eggs and tea.",
    note: "Baked fresh by a neighbourhood bakery.",
  },
  {
    slug: "cream-top-greek-yoghurt",
    name: "Tiger-nut cultured yoghurt",
    category: "Groceries",
    price: 3200,
    unit: "450g tub",
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=85",
    tone: "lilac",
    description: "Thick, cool and naturally tangy with a gentle tiger-nut finish for breakfast or a chilled snack.",
    note: "Made in small batches with no added sugar.",
  },
  {
    slug: "golden-hour-honey",
    name: "Ogbomoso wildflower honey",
    category: "Groceries",
    price: 5200,
    unit: "350ml jar",
    emoji: "🍯",
    image: "https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&w=900&q=85",
    tone: "honey",
    badge: "Customer favourite",
    description: "Floral, amber honey with a soft finish from flowering groves in Ogbomoso. Lovely over toast or pap.",
    note: "Single-origin and gently filtered.",
  },
  {
    slug: "pink-guava-sparkler",
    name: "Chilled zobo blend",
    category: "Groceries",
    price: 2800,
    unit: "4 × 330ml bottles",
    emoji: "🩷",
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=85",
    tone: "pink",
    badge: "New sip",
    description: "A bright hibiscus zobo blend with ginger, pineapple and a little lime. Best served very cold.",
    note: "Brewed locally with real fruit and spices.",
  },
  {
    slug: "market-day-avocado",
    name: "Market avocado pack",
    category: "Groceries",
    price: 3800,
    unit: "pack / 3 pieces",
    emoji: "🥑",
    image: "https://images.unsplash.com/photo-1523049673857-5a3e5b6b5c7a?auto=format&fit=crop&w=900&q=85",
    tone: "avocado",
    description: "Creamy, buttery avocados ready for peppered toast, salads, sandwiches and proper guacamole.",
    note: "Ripeness checked by hand before dispatch.",
  },
  {
    slug: "slow-sunday-pasta",
    name: "Jollof tomato base",
    category: "Groceries",
    price: 3900,
    unit: "500g pouch",
    emoji: "🍝",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=85",
    tone: "tomato",
    description: "A rich tomato, pepper and onion base for quick jollof rice, stew, pasta and weeknight cooking.",
    note: "Blended locally with no artificial colour.",
  },
  {
    slug: "wildflower-table-bouquet",
    name: "Tropical market bouquet",
    category: "Gifts",
    price: 7600,
    unit: "1 seasonal bunch",
    emoji: "💐",
    image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=900&q=85",
    tone: "flower",
    badge: "Weekend mood",
    description: "A loose, colourful bunch of tropical stems to make the kitchen feel like it has plans.",
    note: "Seasonal stems will vary by local grower.",
  },
  {
    slug: "morning-roast-coffee",
    name: "Nigerian morning roast",
    category: "Groceries",
    price: 6400,
    unit: "250g beans",
    emoji: "☕",
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=85",
    tone: "coffee",
    description: "Chocolatey, nutty and easy to love, roasted for bright mornings and slow weekend breakfasts.",
    note: "Roasted weekly in Lagos from Nigerian beans.",
  },
  {
    slug: "salted-caramel-granola",
    name: "Kunu crunch granola",
    category: "Groceries",
    price: 5600,
    unit: "400g pouch",
    emoji: "🥜",
    image: "https://images.unsplash.com/photo-1517093728432-a0440f8d45af?auto=format&fit=crop&w=900&q=85",
    tone: "caramel",
    description: "Toasty oats, millet, roasted nuts and a gentle kunu-spice warmth for a proper breakfast crunch.",
    note: "Naturally sweetened and made locally.",
  },
  {
    slug: "soft-touch-dish-soap",
    name: "Lemongrass dish wash",
    category: "Home & Living",
    price: 2900,
    unit: "500ml bottle",
    emoji: "🫧",
    image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=900&q=85",
    tone: "blue",
    description: "A gentle lemongrass-scented clean for everyday plates, pots and post-party evidence.",
    note: "Plant-based formula made in Nigeria.",
  },
  {
    slug: "soundpods-wireless-earbuds",
    name: "SoundPods wireless earbuds",
    category: "Electronics",
    price: 28500,
    unit: "1 pair",
    emoji: "🎧",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85",
    tone: "blue",
    badge: "Tech favourite",
    description: "Compact wireless earbuds with clear calls, a comfortable fit and a charging case for your daily commute.",
    note: "Fast local delivery and easy returns.",
  },
  {
    slug: "klemview-smart-television",
    name: "KlemView smart television",
    category: "Electronics",
    price: 389000,
    unit: "43-inch 4K TV",
    emoji: "📺",
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=900&q=85",
    tone: "blue",
    badge: "New arrival",
    description: "A crisp 4K smart screen for football nights, family films and everything you stream after work.",
    note: "Warranty included. Delivery scheduling available.",
  },
  {
    slug: "swiftcharge-power-bank",
    name: "SwiftCharge power bank",
    category: "Electronics",
    price: 32000,
    unit: "20,000mAh",
    emoji: "🔋",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=85",
    tone: "blue",
    badge: "Everyday essential",
    description: "Reliable portable power with two USB outputs for busy days, travel and unpredictable power cuts.",
    note: "Tested before dispatch.",
  },
  {
    slug: "pocket-bluetooth-speaker",
    name: "Pocket Bluetooth speaker",
    category: "Electronics",
    price: 46500,
    unit: "1 speaker",
    emoji: "🔊",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=85",
    tone: "blue",
    description: "Room-filling sound in a compact speaker with a durable finish for kitchens, balconies and weekends away.",
    note: "Up to 12 hours of playback.",
  },
  {
    slug: "rust-bomber-jacket",
    name: "Rust bomber jacket",
    category: "Women",
    price: 38500,
    unit: "Sizes S–XL",
    emoji: "🧥",
    image: "/images/p/rust-bomber-jacket.jpg",
    tone: "cream",
    badge: "New",
    description: "A lightweight bomber in a warm rust tone with a soft lining, made to layer over everything from tees to dresses.",
    note: "Easy 7-day returns.",
  },
  {
    slug: "linen-shirt-edit",
    name: "Linen shirt edit",
    category: "Women",
    price: 26000,
    unit: "Set of 3",
    emoji: "👚",
    image: "/images/p/linen-shirt-edit.jpg",
    tone: "cream",
    description: "Breathable linen shirts in a calm neutral palette for hot days, long lunches and weekends away.",
    note: "Pre-washed for a soft hand feel.",
  },
  {
    slug: "classic-crew-tee",
    name: "Classic crew tee",
    category: "Men",
    price: 12500,
    unit: "Sizes S–XXL",
    emoji: "👕",
    image: "/images/p/classic-crew-tee.jpg",
    tone: "cream",
    description: "A heavyweight cotton tee with a clean neckline and a fit that holds its shape wash after wash.",
    note: "100% combed cotton.",
  },
  {
    slug: "suede-derby-shoes",
    name: "Suede derby shoes",
    category: "Men",
    price: 36000,
    unit: "Sizes 40–46",
    emoji: "👞",
    image: "/images/p/suede-derby-shoes.jpg",
    tone: "cream",
    badge: "New",
    description: "Soft suede derbies in a muted sage with a flexible sole, smart enough for the office and easy enough for the weekend.",
    note: "Includes a protective care kit.",
  },
  {
    slug: "heritage-hoodie",
    name: "Heritage hoodie",
    category: "Men",
    price: 24500,
    unit: "Sizes S–XXL",
    emoji: "🧶",
    image: "/images/p/heritage-hoodie.jpg",
    tone: "cream",
    badge: "Customer favourite",
    description: "A relaxed, brushed-fleece hoodie with a roomy hood and a cosy lining for cool evenings.",
    note: "Pre-shrunk fabric.",
  },
  {
    slug: "structured-handbag",
    name: "Structured top-handle bag",
    category: "Accessories",
    price: 42000,
    unit: "1 bag",
    emoji: "👜",
    image: "/images/p/structured-handbag.jpg",
    tone: "cream",
    description: "A glossy top-handle bag with a structured shape and a polished clasp that lifts any outfit.",
    note: "Dust bag included.",
  },
  {
    slug: "canvas-tote",
    name: "Everyday canvas tote",
    category: "Accessories",
    price: 9500,
    unit: "1 tote",
    emoji: "🛍️",
    image: "/images/p/canvas-tote.jpg",
    tone: "cream",
    description: "A sturdy, roomy canvas tote for market runs, books and everything in between.",
    note: "Reinforced handles.",
  },
  {
    slug: "everyday-backpack",
    name: "Everyday backpack",
    category: "Accessories",
    price: 28000,
    unit: "1 backpack",
    emoji: "🎒",
    image: "/images/p/everyday-backpack.jpg",
    tone: "cream",
    badge: "New",
    description: "A clean navy backpack with a padded laptop sleeve and enough space for the whole day.",
    note: "Water-resistant fabric.",
  },
  {
    slug: "classic-sunglasses",
    name: "Classic sunglasses",
    category: "Accessories",
    price: 18500,
    unit: "1 pair",
    emoji: "🕶️",
    image: "/images/p/classic-sunglasses.jpg",
    tone: "cream",
    description: "Timeless frames with UV-protective lenses that suit almost every face shape.",
    note: "UV400 protection.",
  },
  {
    slug: "leather-wallet",
    name: "Leather wallet",
    category: "Accessories",
    price: 16500,
    unit: "1 wallet",
    emoji: "👛",
    image: "/images/p/leather-wallet.jpg",
    tone: "cream",
    description: "A slim bifold in rich, full-grain leather that softens beautifully with age.",
    note: "Six card slots and a coin pocket.",
  },
  {
    slug: "smart-fitness-watch",
    name: "Smart fitness watch",
    category: "Electronics",
    price: 89000,
    unit: "1 watch",
    emoji: "⌚",
    image: "/images/p/smart-fitness-watch.jpg",
    tone: "cream",
    badge: "Tech favourite",
    description: "Track workouts, heart rate and sleep with a bright always-on display and multi-day battery life.",
    note: "Warranty included.",
  },
  {
    slug: "minimal-watch",
    name: "Minimal watch",
    category: "Electronics",
    price: 54000,
    unit: "1 watch",
    emoji: "⌚",
    image: "/images/p/minimal-watch.jpg",
    tone: "cream",
    description: "A clean, minimalist watch with a soft strap and a face that goes with everything.",
    note: "Water resistant to 30m.",
  },
  {
    slug: "wireless-headphones",
    name: "Wireless headphones",
    category: "Electronics",
    price: 38500,
    unit: "1 pair",
    emoji: "🎧",
    image: "/images/p/wireless-headphones.jpg",
    tone: "cream",
    description: "Comfortable over-ear headphones with rich sound, a long battery and quick Bluetooth pairing.",
    note: "Up to 30 hours of playback.",
  },
  {
    slug: "ceramic-plant-pot",
    name: "Ceramic plant pot",
    category: "Home & Living",
    price: 8500,
    unit: "1 pot",
    emoji: "🪴",
    image: "/images/p/ceramic-plant-pot.jpg",
    tone: "cream",
    description: "A soft mint ceramic pot with drainage that gives any shelf, desk or windowsill a fresh lift.",
    note: "Plant not included.",
  },
  {
    slug: "velvet-sofa",
    name: "Velvet three-seater sofa",
    category: "Home & Living",
    price: 420000,
    unit: "3-seater",
    emoji: "🛋️",
    image: "/images/p/velvet-sofa.jpg",
    tone: "cream",
    badge: "New arrival",
    description: "A deep emerald velvet sofa on solid wooden legs, built for slow evenings and full living rooms.",
    note: "Delivery scheduling available.",
  },
  {
    slug: "mid-century-armchair",
    name: "Mid-century armchair",
    category: "Home & Living",
    price: 185000,
    unit: "1 chair",
    emoji: "🪑",
    image: "/images/p/mid-century-armchair.jpg",
    tone: "cream",
    description: "A sculpted armchair in sunny mustard with warm wooden legs, perfect for a reading corner.",
    note: "Assembly service available.",
  },
  {
    slug: "aromatic-candle",
    name: "Aromatic candle",
    category: "Gifts",
    price: 7500,
    unit: "220g jar",
    emoji: "🕯️",
    image: "/images/p/aromatic-candle.jpg",
    tone: "cream",
    badge: "Gift favourite",
    description: "A hand-poured soy candle with a warm, calming scent and a long, even burn.",
    note: "Burns for up to 45 hours.",
  },
  {
    slug: "restorative-hair-mask",
    name: "Restorative hair mask",
    category: "Beauty",
    price: 11500,
    unit: "200ml tube",
    emoji: "💆",
    image: "/images/p/restorative-hair-mask.jpg",
    tone: "cream",
    description: "A deep-conditioning mask that restores softness and shine to dry or colour-treated hair.",
    note: "Free from parabens.",
  },
  {
    slug: "body-lotion",
    name: "Nourishing body lotion",
    category: "Beauty",
    price: 9800,
    unit: "250ml tube",
    emoji: "🧴",
    image: "/images/p/body-lotion.jpg",
    tone: "cream",
    description: "A silky, fast-absorbing lotion that keeps skin soft and comfortable all day.",
    note: "Dermatologist tested.",
  },
  {
    slug: "daily-cleanser",
    name: "Daily skin cleanser",
    category: "Beauty",
    price: 8900,
    unit: "150ml tube",
    emoji: "🧼",
    image: "/images/p/daily-cleanser.jpg",
    tone: "cream",
    description: "A gentle everyday cleanser that lifts dirt and oil without leaving skin tight.",
    note: "Suitable for sensitive skin.",
  },
  {
    slug: "makeup-palette",
    name: "Everyday makeup edit",
    category: "Beauty",
    price: 24000,
    unit: "Set of 5",
    emoji: "💄",
    image: "/images/p/makeup-palette.jpg",
    tone: "cream",
    description: "A curated set of blush, bronzer and neutrals for a fresh, effortless face in minutes.",
    note: "Cruelty-free formulas.",
  },
  {
    slug: "yoga-mat-set",
    name: "Yoga mat",
    category: "Sports",
    price: 14500,
    unit: "1 mat",
    emoji: "🧘",
    image: "/images/p/yoga-mat-set.jpg",
    tone: "cream",
    description: "A cushioned, non-slip mat that grips well and rolls up neatly for the gym or living room.",
    note: "Includes carry strap.",
  },
  {
    slug: "strength-training-bar",
    name: "Strength training bar",
    category: "Sports",
    price: 65000,
    unit: "1 bar",
    emoji: "🏋️",
    image: "/images/p/strength-training-bar.jpg",
    tone: "cream",
    description: "A knurled steel training bar built for squats, presses and deadlifts at home or in the gym.",
    note: "Supports up to 200kg.",
  },
  {
    slug: "performance-running-shoes",
    name: "Performance running shoes",
    category: "Sports",
    price: 32000,
    unit: "Sizes 40–46",
    emoji: "👟",
    image: "/images/p/performance-running-shoes.jpg",
    tone: "cream",
    description: "Lightweight running shoes with a cushioned sole and breathable upper for daily miles.",
    note: "Free returns within 7 days.",
  },
  {
    slug: "festive-gift-box",
    name: "Festive gift box",
    category: "Gifts",
    price: 12000,
    unit: "1 box",
    emoji: "🎁",
    image: "/images/p/festive-gift-box.jpg",
    tone: "cream",
    description: "A beautifully wrapped gift box ready for birthdays, thank-yous and every celebration in between.",
    note: "Free gift note included.",
  },
];

const merchandising: Record<string, Pick<Product, "rating" | "reviews" | "compareAt">> = {
  "sunrise-citrus-box": { rating: 4.8, reviews: 214 },
  "garden-crunch-lettuce": { rating: 4.6, reviews: 98, compareAt: 2900 },
  "cloud-nine-sourdough": { rating: 4.9, reviews: 342 },
  "cream-top-greek-yoghurt": { rating: 4.5, reviews: 76 },
  "golden-hour-honey": { rating: 4.9, reviews: 418 },
  "pink-guava-sparkler": { rating: 4.4, reviews: 61, compareAt: 3400 },
  "market-day-avocado": { rating: 4.7, reviews: 129 },
  "slow-sunday-pasta": { rating: 4.6, reviews: 187 },
  "wildflower-table-bouquet": { rating: 4.8, reviews: 53 },
  "morning-roast-coffee": { rating: 4.7, reviews: 265, compareAt: 7400 },
  "salted-caramel-granola": { rating: 4.5, reviews: 112 },
  "soft-touch-dish-soap": { rating: 4.6, reviews: 144 },
  "soundpods-wireless-earbuds": { rating: 4.7, reviews: 308, compareAt: 34000 },
  "klemview-smart-television": { rating: 4.8, reviews: 87, compareAt: 429000 },
  "swiftcharge-power-bank": { rating: 4.6, reviews: 193 },
  "pocket-bluetooth-speaker": { rating: 4.5, reviews: 76, compareAt: 52000 },

  "rust-bomber-jacket": { rating: 4.8, reviews: 164, compareAt: 45000 },
  "linen-shirt-edit": { rating: 4.7, reviews: 92 },
  "classic-crew-tee": { rating: 4.6, reviews: 311 },
  "suede-derby-shoes": { rating: 4.7, reviews: 78 },
  "heritage-hoodie": { rating: 4.8, reviews: 276, compareAt: 29000 },
  "structured-handbag": { rating: 4.9, reviews: 203 },
  "canvas-tote": { rating: 4.5, reviews: 148 },
  "everyday-backpack": { rating: 4.9, reviews: 148 },
  "classic-sunglasses": { rating: 4.6, reviews: 203, compareAt: 22000 },
  "leather-wallet": { rating: 4.8, reviews: 196 },
  "smart-fitness-watch": { rating: 4.5, reviews: 276, compareAt: 99000 },
  "minimal-watch": { rating: 4.4, reviews: 308 },
  "wireless-headphones": { rating: 4.6, reviews: 187 },
  "ceramic-plant-pot": { rating: 4.7, reviews: 93 },
  "velvet-sofa": { rating: 4.8, reviews: 41, compareAt: 480000 },
  "mid-century-armchair": { rating: 4.7, reviews: 56 },
  "aromatic-candle": { rating: 4.7, reviews: 419 },
  "restorative-hair-mask": { rating: 4.6, reviews: 122 },
  "body-lotion": { rating: 4.8, reviews: 233, compareAt: 11500 },
  "daily-cleanser": { rating: 4.5, reviews: 175 },
  "makeup-palette": { rating: 4.7, reviews: 109 },
  "yoga-mat-set": { rating: 4.7, reviews: 121 },
  "strength-training-bar": { rating: 4.6, reviews: 38 },
  "performance-running-shoes": { rating: 4.7, reviews: 245 },
  "festive-gift-box": { rating: 4.9, reviews: 88 },
};

for (const product of products) Object.assign(product, merchandising[product.slug]);
products.push(...extraProducts);
for (const category of categories) category.count = String(products.filter((product) => product.category === category.name).length);

export const discountPercent = (product: Pick<Product, "price" | "compareAt">) =>
  product.compareAt && product.compareAt > product.price ? Math.round((1 - product.price / product.compareAt) * 100) : 0;

export const curatedSlugs = {
  featured: ["white-leather-sneakers", "smart-fitness-watch", "ceramic-table-lamp", "everyday-backpack", "ivory-blazer", "linen-bedding-set", "wooden-building-blocks", "cast-iron-skillet"],
  newArrivals: ["copper-pour-over-kettle", "block-heel-pumps", "wooden-train-set", "navy-knit-polo"],
  bestSellers: ["structured-handbag", "baby-sage-romper", "speckled-mug-set", "leather-wallet"],
};

export const pickProducts = (list: Product[], slugs: string[], fallbackStart = 0) => {
  const picked = slugs.map((slug) => list.find((product) => product.slug === slug)).filter((product): product is Product => Boolean(product));
  return picked.length >= slugs.length ? picked : list.slice(fallbackStart, fallbackStart + slugs.length);
};

export const formatNaira = (amount: number) =>
  new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(amount);

export const getProduct = (slug: string) => products.find((product) => product.slug === slug);

export const getCategory = (slug: string) => categories.find((category) => category.slug === slug);

export const categoryProducts = (slug: string) => {
  const category = getCategory(slug);
  return category ? products.filter((product) => product.category === category.name) : products;
};
